# Generated by Django 5.2.14 on 2026-06-26 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
