# Generated by Django 5.2.14 on 2026-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
