# Generated by Django 5.2.14 on 2026-06-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_registration_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='semester',
            field=models.CharField(default='S1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='student_id',
            field=models.CharField(default='ST000', max_length=30),
            preserve_default=False,
        ),
    ]
